import os

Import('*')

# get a list of source files
unittest_src = set()

for f in env.Glob('*.cc'):
	path, file = os.path.split(str(f) )
	unittest_src.add(file)
	
unittest_objs = env.Object(list(unittest_src) )

unittests_name = 'NisheUnittests%s' % (libsuffix)
unittests = env.Program('bin/%s' % (unittests_name),
			unittest_objs,
			LIBPATH = ['#/lib'], LIBS = [libnishe_name, 'gtest', 'gtest_main'])

env.Depends(unittests, nishe_lib)
env.InstallAs(target = '#/bin/%s' % (unittests_name),
		source = unittests)